### ISSUE TITLE
加载其他的模型会报维度错误，请问咋解决

### ISSUE THREAD

**Issue by liuCodeBoy** [zstar1003/VITS#2]
Traceback (most recent call last):
  File "/home/lxq/Desktop/VITS-main/main.py", line 21, in <module>
    utils.load_checkpoint('model/Paimon1.pth', model)
  File "/home/lxq/Desktop/VITS-main/utils.py", line 42, in load_checkpoint
    model.load_state_dict(new_state_dict)
  File "/home/lxq/anaconda3/envs/tts-3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SynthesizerTrn:
	size mismatch for enc_p.emb.weight: copying a param with shape torch.Size([52, 192]) from checkpoint, the shape in current model is torch.Size([178, 192]).

**Comment by zstar1003** [comment]
如果加载其它的模型，必须同样附带上相应的config文件

**Comment by liuCodeBoy** [comment]
您是指  biaobei_base.json 这样的config文件吗 搭配的 paimon 模型吗 
 我就是找的配套的模型以及json配置文件，依然会报维度不匹配错 我打开看到里面的配置和你用的 biaobei_base.json 的字段会有些不同如下:
 {
  "train": {
    "log_interval": 200,
    "eval_interval": 1000,
    "seed": 1234,
    "epochs": 40000,
    "learning_rate": 2e-4,
    "betas": [0.8, 0.99],
    "eps": 1e-9,
    "batch_size": 46,
    "fp16_run": true,
    "lr_decay": 0.999875,
    "segment_size": 8192,
    "init_lr_ratio": 1,
    "warmup_epochs": 0,
    "c_mel": 45,
    "c_kl": 1.0
  },
  "data": {
    "training_files":"filelists/paimon_6k_train_chs.txt.cleaned",
    "validation_files":"filelists/paimon_6k_val_chs.txt.cleaned",
    "text_cleaners":["chinese_cleaners"],
    "max_wav_value": 32768.0,
    "sampling_rate": 48000,
    "filter_length": 1024,
    "hop_length": 256,
    "win_length": 1024,
    "n_mel_channels": 80,
    "mel_fmin": 0.0,
    "mel_fmax": null,
    "add_blank": true,
    "n_speakers": 0,
    "cleaned_text": true
  },
  "model": {
    "inter_channels": 192,
    "hidden_channels": 192,
    "filter_channels": 768,
    "n_heads": 2,
    "n_layers": 6,
    "kernel_size": 3,
    "p_dropout": 0.1,
    "resblock": "1",
    "resblock_kernel_sizes": [3,7,11],
    "resblock_dilation_sizes": [[1,3,5], [1,3,5], [1,3,5]],
    "upsample_rates": [8,8,2,2],
    "upsample_initial_channel": 512,
    "upsample_kernel_sizes": [16,16,4,4],
    "n_layers_q": 3,
    "use_spectral_norm": false,
    "gin_channels": 256
  },
  "speakers": ["paimon"],
  "symbols": ["_", "\uff0c", "\u3002", "\uff01", "\uff1f", "\u2014", "\u2026", "\u3105", "\u3106", "\u3107", "\u3108", "\u3109", "\u310a", "\u310b", "\u310c", "\u310d", "\u310e", "\u310f", "\u3110", "\u3111", "\u3112", "\u3113", "\u3114", "\u3115", "\u3116", "\u3117", "\u3118", "\u3119", "\u311a", "\u311b", "\u311c", "\u311d", "\u311e", "\u311f", "\u3120", "\u3121", "\u3122", "\u3123", "\u3124", "\u3125", "\u3126", "\u3127", "\u3128", "\u3129", "\u02c9", "\u02ca", "\u02c7", "\u02cb", "\u02d9", " "]
}


是因为增加了些许配置项导致的吗，不太懂希望大大解惑，我的python环境是3.10.8

**Comment by zstar1003** [comment]
是这样的json文件，增加的配置项问题不大，配置项主要看model这里面的参数，看报错信息是192这个维度出现问题，可能是模型的`inter_channels`或者`hidden_channels`和配置文件的对不上，具体问题可以把模型结构导出来看看
